#!/usr/bin/env python3
import argparse
import concurrent.futures
import json
import os
import subprocess
import sys
from pathlib import Path
import shutil
import time
import uuid

import boto3

from workdir_utils import cleanup_work_dir, make_work_dir, should_keep_workdir


def run_cmd(cmd: list[str], cwd: Path | None = None) -> None:
    print("[run]", " ".join(cmd))
    res = subprocess.run(cmd, cwd=str(cwd) if cwd else None)
    if res.returncode != 0:
        raise SystemExit(res.returncode)


def s3_parse_uri(uri: str) -> tuple[str, str]:
    assert uri.startswith("s3://"), f"Not an s3 uri: {uri}"
    no = uri[5:]
    bucket, key = no.split("/", 1)
    return bucket, key


def s3_download(s3, uri: str, dest: Path) -> None:
    b, k = s3_parse_uri(uri)
    dest.parent.mkdir(parents=True, exist_ok=True)
    print(f"[s3] download {uri} -> {dest}")
    s3.download_file(b, k, str(dest))


def s3_upload_dir(s3, src_dir: Path, s3_prefix: str, include_suffix: str = ".png") -> None:
    b, k_prefix = s3_parse_uri(s3_prefix)
    files = sorted(src_dir.rglob(f"*{include_suffix}"))
    if not files:
        return
    workers = max(1, int(os.environ.get("VPG_S3_UPLOAD_WORKERS", "32")))

    def _upload_one(f: Path) -> None:
        rel = f.relative_to(src_dir)
        key = f"{k_prefix.rstrip('/')}/{rel.as_posix()}"
        print(f"[s3] upload {f} -> s3://{b}/{key}")
        s3.upload_file(str(f), b, key)

    print(f"[s3] parallel upload: files={len(files)} workers={workers}")
    with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as ex:
        futs = [ex.submit(_upload_one, f) for f in files]
        for fut in concurrent.futures.as_completed(futs):
            fut.result()


def main():
    ap = argparse.ArgumentParser(description="Render worker: downloads inputs from S3, configures scene, renders a frame range, uploads frames to S3.")
    ap.add_argument("--director_s3", required=True, help="s3://.../director_visemes.json")
    ap.add_argument("--generator_inputs_s3", required=True, help="s3://.../manifests/generator_inputs.json")
    ap.add_argument("--scene_s3", default="", help="Optional prepared scene .blend in S3 (generated by gpu_prepare_scene.py). If provided, role configuration is assumed already applied.")
    ap.add_argument("--frames_out_s3_prefix", required=True, help="s3://bucket/jobs/<id>/frames")
    ap.add_argument("--frame_start", type=int, required=True)
    ap.add_argument("--frame_end", type=int, required=True)
    ap.add_argument("--transparent", action="store_true", help="Render PNG RGBA frames")
    args = ap.parse_args()

    s3 = boto3.client("s3", region_name=os.environ.get("AWS_REGION") or os.environ.get("AWS_DEFAULT_REGION"))

    project_root = Path(__file__).resolve().parents[1]
    work = make_work_dir("vpg_worker_render_")
    try:
        local_director = work / "director_visemes.json"
        local_gen_inputs = work / "generator_inputs.json"
        s3_download(s3, args.director_s3, local_director)
        s3_download(s3, args.generator_inputs_s3, local_gen_inputs)
        # Ensure downstream Blender scripts read the *job* generator_inputs, not a baked-in file.
        os.environ["VPG_GENERATOR_INPUTS_JSON"] = str(local_gen_inputs)

        # Decide render engine override from generator inputs (so we don't depend on any baked defaults).
        engine_cli = None
        quality_cli = None
        try:
            gi = json.loads(local_gen_inputs.read_text())
            run_cfg = gi.get("run") or {}
            re = str(run_cfg.get("render_engine") or "").strip().lower()
            if re in ("blender_eevee", "eevee"):
                engine_cli = "eevee"
            elif re in ("blender_workbench", "workbench"):
                engine_cli = "workbench"
            elif re in ("blender_cycles", "cycles"):
                engine_cli = "cycles"
            # Optional: allow a simple quality knob for Eevee via generator_inputs.json
            # (fast/full). If omitted, the Blender script default applies.
            q = str(run_cfg.get("quality") or "").strip().lower()
            if q in ("fast", "full"):
                quality_cli = q
        except Exception:
            engine_cli = None
            quality_cli = None

        # Prepare temp scene: either download a prepared scene, or copy base scene and configure roles
        cfg_path = project_root / "run_full_video_creation_sequence.config.json"
        cfg = json.loads(cfg_path.read_text())
        # IMPORTANT: the repo config may contain a Mac path. In containers/Batch we must honor env overrides.
        blender_bin = (
            os.environ.get("VPG_BLENDER_BIN")
            or os.environ.get("VPG_BLENDER_BIN_PATH")
            or cfg.get("blender_binary")
            or "/usr/local/bin/blender"
        )
        ts_scene = work / "work_scene.blend"

        # NOTE: Eevee/Workbench use OpenGL. Running under Xvfb often forces software GL,
        # which can be dramatically slower than running headless with GPU/EGL.
        # We therefore only use xvfb-run when explicitly requested AND not rendering Eevee/Workbench
        # (unless forced).
        force_xvfb = (os.environ.get("VPG_FORCE_XVFB") or "").strip() == "1"
        want_xvfb = os.environ.get("VPG_XVFB") == "1"
        use_xvfb = bool(want_xvfb and (force_xvfb or (engine_cli not in ("eevee", "workbench"))))
        pre = ["xvfb-run", "-a", "-s", "-screen 0 1920x1080x24"] if use_xvfb else []

        if args.scene_s3:
            # Use prepared scene (already has role collections + configured materials/selectors)
            s3_download(s3, args.scene_s3, ts_scene)
            input_scene = ts_scene
            base_scene_path = None
        else:
            base_scene = cfg.get("base_scene_blend") or "scenes/base_scene.blend"
            base_scene_path = (project_root / base_scene).resolve()
            if not base_scene_path.exists():
                raise SystemExit(f"Base scene not found: {base_scene_path}")
            input_scene = None

        # Render the requested range with transparent frames using single-process Blender pipeline.
        # Use a unique output per run to avoid cross-job contamination.
        run_id = uuid.uuid4().hex[:8]
        try:
            # Try to derive job id from frames prefix: .../jobs/<jobId>/frames
            p = args.frames_out_s3_prefix
            if "/jobs/" in p:
                run_id = p.split("/jobs/", 1)[1].split("/", 1)[0][:8] or run_id
            elif "/render_cache/" in p:
                # Deterministic render cache stem: .../render_cache/<renderCacheKey>/frames
                run_id = p.split("/render_cache/", 1)[1].split("/", 1)[0][:8] or run_id
        except Exception:
            pass
        out_video = work / f"batch_render_{run_id}.mp4"
        frames_dir = out_video.parent / f"{out_video.stem}_frames"
        # Clear any prior frames for this run_id to ensure we don't upload stale PNGs if Blender fails.
        if frames_dir.exists():
            shutil.rmtree(frames_dir, ignore_errors=True)
        start_ts = time.time()
        single_blender_py = project_root / "scripts" / "blender_pipeline_single_process.py"
        render_cmd = pre + [
            str(blender_bin), "-b", str((input_scene or base_scene_path or ts_scene)),
            "--python-exit-code", "1",
            "--python", str(single_blender_py),
            "--",
            "--generator_inputs_json", str(local_gen_inputs),
            "--run_configure_roles",
            "--hdri_from_config", str(cfg_path),
            "--director_json", str(local_director),
            "--out_video", str(out_video),
            "--frame_start", str(int(args.frame_start)),
            "--frame_end", str(int(args.frame_end)),
            "--no_audio",
        ]
        if input_scene:
            render_cmd += ["--input_scene", str(input_scene)]
        else:
            render_cmd += ["--base_scene_blend", str(base_scene_path), "--work_scene", str(ts_scene)]
        if engine_cli:
            render_cmd += ["--engine", engine_cli]
        if quality_cli:
            render_cmd += ["--quality", quality_cli]
        run_cmd(render_cmd)

        # Upload frames back to S3
        if not frames_dir.exists():
            raise SystemExit("[error] frames directory missing; render failed.")
        pngs = sorted(frames_dir.glob("*.png"))
        if not pngs:
            raise SystemExit("[error] no PNG frames produced; render failed.")
        # Sanity: ensure frames are from this run (avoid uploading leftovers).
        newest = max(p.stat().st_mtime for p in pngs)
        if newest < (start_ts - 1.0):
            raise SystemExit("[error] PNG frames appear to be stale (older than this render invocation).")
        s3_upload_dir(s3, frames_dir, args.frames_out_s3_prefix)

        print("[worker_render] done.")
    finally:
        if not should_keep_workdir():
            cleanup_work_dir(work)


if __name__ == "__main__":
    main()


